### ISSUE TITLE
Using Ditto nuget in a manually setup Umbraco solution downgrades Umbraco Core DLLs

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-ditto#122] opened 2015-10-06 12:28 UTC
If you setup an Umbraco site manually (ie, not via Nuget) and you then proceed to install Ditto via nuget, because it has a minimum dependency on an older Umbraco Core, installing Ditto will have the oldest supported version Umbraco.Core installed, replacing the current DLL's in the bin folder and effectively downgrading the DLLs. 

You can run an update on Umbraco.Core to reinstall the newest DLL's, however this doesn't always run smoothly in my experience.

I'm not sure if there is anything we should / can do here, short of not having an Umbraco.Core dependency in the Ditto Nuget file, but thought I'd raise it to have a discussion.

**Comment by leekelleher** [comment] 2015-10-06 12:36
I'd say that is expected behaviour. (NuGet has no knowledge of which Umbraco version you have installed - so installs the minimum dependency version)

You could try the [`IgnoreDependencies`](https://docs.nuget.org/consume/package-manager-console-powershell-reference#install-package) flag?

    Install-Package Our.Umbraco.Ditto -IgnoreDependencies

Alternative option could be to use the `DependencyVersion` flag?

There's some info about this on the NuGet blog:
http://blog.nuget.org/20131216/update-all-experience-explained.html

**Comment by JimBobSquarePants** [comment] 2015-10-08 00:39
Hmmm... I wonder. Is there any harm in not listing Umbraco as a dependency in the Nuget package? We'd probably have to mess around with our build process to ensure this. 

The behaviour, as it is, would be the expected behaviour as far as I can see from the documentation.

**Comment by leekelleher** [comment] 2015-10-08 09:31
IMHO, removing the dependency reference for UmbracoCms.Core would suggest that Ditto works without Umbraco, which it doesn't.

To me, the issue is about NuGet making assumptions - with the `DependencyVersion` flag defaulting to `Lowest`, whereas prior to NuGet v2.8, the default was `HighestPatch`.

**Comment by leekelleher** [comment] 2015-11-12 17:52
Closing this one, we can re-open if anyone feels strongly about it.

**Closed by leekelleher** 2015-11-12 17:52 UTC
Labels: discussion
